---
k3s_server_location: "/var/lib/rancher/k3s"
systemd_dir: "/etc/systemd/system"  # noqa var-naming[no-role-prefix]
api_port: 6443  # noqa var-naming[no-role-prefix]
kubeconfig: ~/.kube/config.new  # noqa var-naming[no-role-prefix]
user_kubectl: true  # noqa var-naming[no-role-prefix]
cluster_context: k3s-ansible  # noqa var-naming[no-role-prefix]
server_group: server  # noqa var-naming[no-role-prefix]
agent_group: agent  # noqa var-naming[no-role-prefix]
use_external_database: false # noqa var-naming[no-role-prefix]
extra_server_args: "" # noqa var-naming[no-role-prefix]

kube_vip_arp: true # noqa var-naming[no-role-prefix]
kube_vip_iface: # noqa var-naming[no-role-prefix]
kube_vip_tag_version: v0.7.2 # noqa var-naming[no-role-prefix]

kube_vip_bgp: false # noqa var-naming[no-role-prefix]
kube_vip_bgp_routerid: 127.0.0.1 # noqa var-naming[no-role-prefix]
kube_vip_bgp_as: "64513" # noqa var-naming[no-role-prefix]
kube_vip_bgp_peeraddress: 192.168.30.1 # noqa var-naming[no-role-prefix]
kube_vip_bgp_peeras: "64512" # noqa var-naming[no-role-prefix]

kube_vip_bgp_peers: [] # noqa var-naming[no-role-prefix]
kube_vip_bgp_peers_groups: ['k3s_master'] # noqa var-naming[no-role-prefix]
