---
- name: Cluster prep
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: prereq
    - role: raspberrypi

- name: Setup k3s server
  hosts: server
  become: true
  roles:
    - role: k3s_server

- name: Setup k3s agent
  hosts: agent
  become: true
  roles:
    - role: k3s_agent
